version: '3.6'

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default
      - chats
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-chats}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-chats}
      - POSTGRES_DB=${POSTGRES_DB:-chats}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  postgres:


networks:
  chats:
    external: true
