version: '3.6'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: chats
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - default
      - chats

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    networks:
      - default
      - chats
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017/

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  mongodb_data_container:

networks:
  chats:
    external: true
